# Generated by Django 4.1.13 on 2024-04-21 21:57

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(editable=False, max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('messages', djongo.models.fields.ArrayField(model_container=api.models.Message, model_form_class=api.models.MessageForm)),
            ],
        ),
    ]
