# Generated by Django 4.1.13 on 2024-05-02 02:39

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='messages',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='user',
            name='messages',
            field=djongo.models.fields.JSONField(default=[]),
        ),
    ]
