# Generated by Django 4.1.13 on 2024-04-21 22:47

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='messages',
            field=djongo.models.fields.ArrayField(model_container=api.models.Message, model_form_class=api.models.MessageForm, null=True),
        ),
    ]
