# Generated by Django 4.1.13 on 2024-04-21 22:54

import api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email_alter_user_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='messages',
            field=djongo.models.fields.ArrayField(default=[], model_container=api.models.Message, model_form_class=api.models.MessageForm),
        ),
    ]
